dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    class: sfPropelDatabase
    param:
      classname: DebugPDO
      dsn: 'mysql:host=localhost;dbname=webschool_test'
      username: appUser
      password: secretPass
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=webschool'
      username: appUser
      password: secretPass
      encoding: utf8
      persistent: true
      pooling: true
