<?php
// auto-generated by sfRoutingConfigHandler
// date: 2014/04/30 16:49:41
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'user',
  'action' => 'index',
), array (
), array (
)),
'register_new_user' => new sfRoute('/registrera-ny-anvandare', array (
  'module' => 'user',
  'action' => 'new',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
