<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/04/30 16:49:41
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
