<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/05/05 15:59:18
$this->security = array (
  'new' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
