# default rules
homepage:
  url:   /
  param: { module: user, action: index }
  
register_new_user:
  url:   /registrera-konto
  param: { module: user, action: new }

edit_user_account:
  url:   /redigera-konto
  param: { module: user, action: edit }

edit_user_password:
  url:   /redigera-losenord
  param: { module: user, action: editpassword }

delete_user_account:
  url:   /radera-konto
  param: { module: user, action: delete }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
