default:
  http_metas:
    content-type: text/html

  metas:
    title:        Webbskola
    #description:  symfony project
    #keywords:     symfony, project
    language:     sv
    #robots:       index, follow

  stylesheets:    [normalize.css, foundation.css, main.css]

  javascripts:    [/js/vendor/custom.modernizr.js, /js/vendor/jquery.js, /js/foundation/foundation.js, /js/foundation/foundation.topbar.js, /js/foundation/foundation.alerts.js]

  has_layout:     on
  layout:         layout
