<?php

/**
 * Base class that represents a row from the 'question' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 05/07/14 22:13:45
 *
 * @package    lib.model.om
 */
abstract class BaseQuestion extends BaseObject  implements Persistent {


  const PEER = 'QuestionPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        QuestionPeer
	 */
	protected static $peer;

	/**
	 * The value for the questionid field.
	 * @var        int
	 */
	protected $questionid;

	/**
	 * The value for the text field.
	 * @var        string
	 */
	protected $text;

	/**
	 * The value for the answerid field.
	 * @var        int
	 */
	protected $answerid;

	/**
	 * @var        Answer
	 */
	protected $aAnswer;

	/**
	 * @var        array Incorrectanswer[] Collection to store aggregation of Incorrectanswer objects.
	 */
	protected $collIncorrectanswers;

	/**
	 * @var        Criteria The criteria used to select the current contents of collIncorrectanswers.
	 */
	private $lastIncorrectanswerCriteria = null;

	/**
	 * @var        array Quiz[] Collection to store aggregation of Quiz objects.
	 */
	protected $collQuizs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collQuizs.
	 */
	private $lastQuizCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseQuestion object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [questionid] column value.
	 * 
	 * @return     int
	 */
	public function getQuestionid()
	{
		return $this->questionid;
	}

	/**
	 * Get the [text] column value.
	 * 
	 * @return     string
	 */
	public function getText()
	{
		return $this->text;
	}

	/**
	 * Get the [answerid] column value.
	 * 
	 * @return     int
	 */
	public function getAnswerid()
	{
		return $this->answerid;
	}

	/**
	 * Set the value of [questionid] column.
	 * 
	 * @param      int $v new value
	 * @return     Question The current object (for fluent API support)
	 */
	public function setQuestionid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->questionid !== $v) {
			$this->questionid = $v;
			$this->modifiedColumns[] = QuestionPeer::QUESTIONID;
		}

		return $this;
	} // setQuestionid()

	/**
	 * Set the value of [text] column.
	 * 
	 * @param      string $v new value
	 * @return     Question The current object (for fluent API support)
	 */
	public function setText($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->text !== $v) {
			$this->text = $v;
			$this->modifiedColumns[] = QuestionPeer::TEXT;
		}

		return $this;
	} // setText()

	/**
	 * Set the value of [answerid] column.
	 * 
	 * @param      int $v new value
	 * @return     Question The current object (for fluent API support)
	 */
	public function setAnswerid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->answerid !== $v) {
			$this->answerid = $v;
			$this->modifiedColumns[] = QuestionPeer::ANSWERID;
		}

		if ($this->aAnswer !== null && $this->aAnswer->getAnswerid() !== $v) {
			$this->aAnswer = null;
		}

		return $this;
	} // setAnswerid()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->questionid = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->text = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->answerid = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 3; // 3 = QuestionPeer::NUM_COLUMNS - QuestionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Question object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAnswer !== null && $this->answerid !== $this->aAnswer->getAnswerid()) {
			$this->aAnswer = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(QuestionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = QuestionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAnswer = null;
			$this->collIncorrectanswers = null;
			$this->lastIncorrectanswerCriteria = null;

			$this->collQuizs = null;
			$this->lastQuizCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseQuestion:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(QuestionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			QuestionPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseQuestion:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseQuestion:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(QuestionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseQuestion:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			QuestionPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAnswer !== null) {
				if ($this->aAnswer->isModified() || $this->aAnswer->isNew()) {
					$affectedRows += $this->aAnswer->save($con);
				}
				$this->setAnswer($this->aAnswer);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = QuestionPeer::QUESTIONID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = QuestionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setQuestionid($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += QuestionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collIncorrectanswers !== null) {
				foreach ($this->collIncorrectanswers as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collQuizs !== null) {
				foreach ($this->collQuizs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAnswer !== null) {
				if (!$this->aAnswer->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAnswer->getValidationFailures());
				}
			}


			if (($retval = QuestionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collIncorrectanswers !== null) {
					foreach ($this->collIncorrectanswers as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collQuizs !== null) {
					foreach ($this->collQuizs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = QuestionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getQuestionid();
				break;
			case 1:
				return $this->getText();
				break;
			case 2:
				return $this->getAnswerid();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = QuestionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getQuestionid(),
			$keys[1] => $this->getText(),
			$keys[2] => $this->getAnswerid(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = QuestionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setQuestionid($value);
				break;
			case 1:
				$this->setText($value);
				break;
			case 2:
				$this->setAnswerid($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = QuestionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setQuestionid($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setText($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setAnswerid($arr[$keys[2]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(QuestionPeer::DATABASE_NAME);

		if ($this->isColumnModified(QuestionPeer::QUESTIONID)) $criteria->add(QuestionPeer::QUESTIONID, $this->questionid);
		if ($this->isColumnModified(QuestionPeer::TEXT)) $criteria->add(QuestionPeer::TEXT, $this->text);
		if ($this->isColumnModified(QuestionPeer::ANSWERID)) $criteria->add(QuestionPeer::ANSWERID, $this->answerid);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(QuestionPeer::DATABASE_NAME);

		$criteria->add(QuestionPeer::QUESTIONID, $this->questionid);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getQuestionid();
	}

	/**
	 * Generic method to set the primary key (questionid column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setQuestionid($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Question (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setText($this->text);

		$copyObj->setAnswerid($this->answerid);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getIncorrectanswers() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addIncorrectanswer($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getQuizs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addQuiz($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setQuestionid(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Question Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     QuestionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new QuestionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Answer object.
	 *
	 * @param      Answer $v
	 * @return     Question The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAnswer(Answer $v = null)
	{
		if ($v === null) {
			$this->setAnswerid(NULL);
		} else {
			$this->setAnswerid($v->getAnswerid());
		}

		$this->aAnswer = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Answer object, it will not be re-added.
		if ($v !== null) {
			$v->addQuestion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Answer object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Answer The associated Answer object.
	 * @throws     PropelException
	 */
	public function getAnswer(PropelPDO $con = null)
	{
		if ($this->aAnswer === null && ($this->answerid !== null)) {
			$c = new Criteria(AnswerPeer::DATABASE_NAME);
			$c->add(AnswerPeer::ANSWERID, $this->answerid);
			$this->aAnswer = AnswerPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAnswer->addQuestions($this);
			 */
		}
		return $this->aAnswer;
	}

	/**
	 * Clears out the collIncorrectanswers collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addIncorrectanswers()
	 */
	public function clearIncorrectanswers()
	{
		$this->collIncorrectanswers = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collIncorrectanswers collection (array).
	 *
	 * By default this just sets the collIncorrectanswers collection to an empty array (like clearcollIncorrectanswers());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initIncorrectanswers()
	{
		$this->collIncorrectanswers = array();
	}

	/**
	 * Gets an array of Incorrectanswer objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Question has previously been saved, it will retrieve
	 * related Incorrectanswers from storage. If this Question is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Incorrectanswer[]
	 * @throws     PropelException
	 */
	public function getIncorrectanswers($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collIncorrectanswers === null) {
			if ($this->isNew()) {
			   $this->collIncorrectanswers = array();
			} else {

				$criteria->add(IncorrectanswerPeer::QUESTIONID, $this->questionid);

				IncorrectanswerPeer::addSelectColumns($criteria);
				$this->collIncorrectanswers = IncorrectanswerPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(IncorrectanswerPeer::QUESTIONID, $this->questionid);

				IncorrectanswerPeer::addSelectColumns($criteria);
				if (!isset($this->lastIncorrectanswerCriteria) || !$this->lastIncorrectanswerCriteria->equals($criteria)) {
					$this->collIncorrectanswers = IncorrectanswerPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastIncorrectanswerCriteria = $criteria;
		return $this->collIncorrectanswers;
	}

	/**
	 * Returns the number of related Incorrectanswer objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Incorrectanswer objects.
	 * @throws     PropelException
	 */
	public function countIncorrectanswers(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collIncorrectanswers === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(IncorrectanswerPeer::QUESTIONID, $this->questionid);

				$count = IncorrectanswerPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(IncorrectanswerPeer::QUESTIONID, $this->questionid);

				if (!isset($this->lastIncorrectanswerCriteria) || !$this->lastIncorrectanswerCriteria->equals($criteria)) {
					$count = IncorrectanswerPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collIncorrectanswers);
				}
			} else {
				$count = count($this->collIncorrectanswers);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Incorrectanswer object to this object
	 * through the Incorrectanswer foreign key attribute.
	 *
	 * @param      Incorrectanswer $l Incorrectanswer
	 * @return     void
	 * @throws     PropelException
	 */
	public function addIncorrectanswer(Incorrectanswer $l)
	{
		if ($this->collIncorrectanswers === null) {
			$this->initIncorrectanswers();
		}
		if (!in_array($l, $this->collIncorrectanswers, true)) { // only add it if the **same** object is not already associated
			array_push($this->collIncorrectanswers, $l);
			$l->setQuestion($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Question is new, it will return
	 * an empty collection; or if this Question has previously
	 * been saved, it will retrieve related Incorrectanswers from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Question.
	 */
	public function getIncorrectanswersJoinAnswer($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collIncorrectanswers === null) {
			if ($this->isNew()) {
				$this->collIncorrectanswers = array();
			} else {

				$criteria->add(IncorrectanswerPeer::QUESTIONID, $this->questionid);

				$this->collIncorrectanswers = IncorrectanswerPeer::doSelectJoinAnswer($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(IncorrectanswerPeer::QUESTIONID, $this->questionid);

			if (!isset($this->lastIncorrectanswerCriteria) || !$this->lastIncorrectanswerCriteria->equals($criteria)) {
				$this->collIncorrectanswers = IncorrectanswerPeer::doSelectJoinAnswer($criteria, $con, $join_behavior);
			}
		}
		$this->lastIncorrectanswerCriteria = $criteria;

		return $this->collIncorrectanswers;
	}

	/**
	 * Clears out the collQuizs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addQuizs()
	 */
	public function clearQuizs()
	{
		$this->collQuizs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collQuizs collection (array).
	 *
	 * By default this just sets the collQuizs collection to an empty array (like clearcollQuizs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initQuizs()
	{
		$this->collQuizs = array();
	}

	/**
	 * Gets an array of Quiz objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Question has previously been saved, it will retrieve
	 * related Quizs from storage. If this Question is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Quiz[]
	 * @throws     PropelException
	 */
	public function getQuizs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizs === null) {
			if ($this->isNew()) {
			   $this->collQuizs = array();
			} else {

				$criteria->add(QuizPeer::QUESTIONID, $this->questionid);

				QuizPeer::addSelectColumns($criteria);
				$this->collQuizs = QuizPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(QuizPeer::QUESTIONID, $this->questionid);

				QuizPeer::addSelectColumns($criteria);
				if (!isset($this->lastQuizCriteria) || !$this->lastQuizCriteria->equals($criteria)) {
					$this->collQuizs = QuizPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastQuizCriteria = $criteria;
		return $this->collQuizs;
	}

	/**
	 * Returns the number of related Quiz objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Quiz objects.
	 * @throws     PropelException
	 */
	public function countQuizs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collQuizs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(QuizPeer::QUESTIONID, $this->questionid);

				$count = QuizPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(QuizPeer::QUESTIONID, $this->questionid);

				if (!isset($this->lastQuizCriteria) || !$this->lastQuizCriteria->equals($criteria)) {
					$count = QuizPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collQuizs);
				}
			} else {
				$count = count($this->collQuizs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Quiz object to this object
	 * through the Quiz foreign key attribute.
	 *
	 * @param      Quiz $l Quiz
	 * @return     void
	 * @throws     PropelException
	 */
	public function addQuiz(Quiz $l)
	{
		if ($this->collQuizs === null) {
			$this->initQuizs();
		}
		if (!in_array($l, $this->collQuizs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collQuizs, $l);
			$l->setQuestion($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Question is new, it will return
	 * an empty collection; or if this Question has previously
	 * been saved, it will retrieve related Quizs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Question.
	 */
	public function getQuizsJoinLesson($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizs === null) {
			if ($this->isNew()) {
				$this->collQuizs = array();
			} else {

				$criteria->add(QuizPeer::QUESTIONID, $this->questionid);

				$this->collQuizs = QuizPeer::doSelectJoinLesson($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(QuizPeer::QUESTIONID, $this->questionid);

			if (!isset($this->lastQuizCriteria) || !$this->lastQuizCriteria->equals($criteria)) {
				$this->collQuizs = QuizPeer::doSelectJoinLesson($criteria, $con, $join_behavior);
			}
		}
		$this->lastQuizCriteria = $criteria;

		return $this->collQuizs;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collIncorrectanswers) {
				foreach ((array) $this->collIncorrectanswers as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collQuizs) {
				foreach ((array) $this->collQuizs as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collIncorrectanswers = null;
		$this->collQuizs = null;
			$this->aAnswer = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseQuestion:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseQuestion::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseQuestion
