<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/04/27 23:26:22

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:host=localhost;dbname=webschool',
  'username' => 'appUser',
  'password' => 'secretPass',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
