<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/05/02 14:52:19

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=webschool',
  'username' => 'appUser',
  'password' => 'secretPass',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
