<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/05/02 14:52:19
$this->security = array (
  'new' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
