<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/01 20:56:38
$this->security = array (
  'new' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
